image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- ps: nuget restore
build:
  project: SetStartupProjects.sln
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test "Tests\Tests.csproj" --framework netcoreapp2.1 --configuration Release --no-build --output bin\Release\netcoreapp2.1

artifacts:
- path: nugets\**\*.nupkg